$installScript = <<SCRIPT
sudo apt update && \
sudo apt install -y  git g++ make python-minimal silversearcher-ag && \
wget https://nodejs.org/dist/v8.3.0/node-v8.3.0-linux-x64.tar.xz && \
tar -xvf node-v8.3.0-linux-x64.tar.xz && \
sudo mv node-v8.3.0-linux-x64/bin/* /usr/bin/ && \
sudo mv node-v8.3.0-linux-x64/lib/* /usr/lib/ && \
cp /vagrant/.tmux.conf /home/vagrant/.tmux.conf
SCRIPT

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/trusty64"

  config.vm.provider "virtualbox" do |v|
    v.memory = 4096
    v.cpus = 1
  end

  config.vm.provision "shell", "inline": $installScript
end
